[tool.poetry]
name = "mytoyota"
description = "Python client for Toyota Connected Services."
authors = ["Simon Grud Hansen <simongrud@gmail.com>"]
license = "MIT"
readme = "README.md"
version = "0.9.3"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = [
    "Toyota",
    "Car",
    "MYT",
]
homepage = "https://github.com/DurgNomis-drol/mytoyota"
repository = "https://github.com/DurgNomis-drol/mytoyota"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/DurgNomis-drol/mytoyota/issues"
"Release Notes" = "https://github.com/DurgNomis-drol/mytoyota/releases"

[tool.poetry.dependencies]
python = "^3.8.1"
langcodes = "^3.1"
httpx = ">=0.18.1"
arrow = "^1.1"
importlib-metadata = {version = "^1.0", python = "<3.8"}
pyjwt = "^2.8.0"
pydantic = "^2.5.1"

[tool.poetry.dev-dependencies]
pre-commit = "^3.0.0"
black = ">=23.9.1"
ruff = "^0.1.5"
pylint = "^3.0.0"
codespell = "^2.0.0"
pytest = "^7.2.0"

[tool.pylint.messages_control]
# Reasons disabled:
# too-many-* - not enforced for the sake of readability
# too-few-* - same as too-many-*
disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "duplicate-code",
    "logging-fstring-interpolation",
]

[tool.pylint.format]
max-line-length = 99

[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    "YTT",
    # Isort
    "I001",
    "I002"
]
line-length = 99
fix = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
