name: "Lint code"

on:
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit"
    runs-on: "ubuntu-latest"
    steps:
      - name: "â¤µï¸ Check out code from GitHub"
        uses: "actions/checkout@v4"
      - name: "ğŸ Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: 3.9
      - name: "âš™ï¸ Install Poetry"
        uses: "abatilo/actions-poetry@v4.0.0"
      - name: "âš™ï¸ Install dependencies"
        run: "poetry install"
      - name: "ğŸš€ Run pre-commit on all files"
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure --color=always
